<a href="https://colab.research.google.com/github/Gew007z/241-2567-820/blob/main/Precourse2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import datetime

now = datetime.datetime.now()
now

datetime.datetime(2025, 1, 7, 6, 30, 37, 388254)

In [ ]:
now.isoformat()

'2025-01-07T06:30:37.388254'

In [ ]:
today = datetime.date.today()
today

datetime.date(2025, 1, 7)

In [ ]:
today.isoformat()

'2025-01-07'

In [ ]:
def circle_area(radius):
   return pi * radius * radius

   circle_area(2)

In [ ]:
import math


In [ ]:
def rectangle_area(height, width):
  return height * width

rectangle_area(4,5)

20

In [ ]:
def conversion(amount, rate=31.33):
  return amount * rate


conversion(30)

939.9

In [ ]:
[i+1 for i in range(100)]

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100]

In [ ]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
conversion(30, 33.3333)

999.999

In [ ]:
file = open("output.csv","w")
file.write("date,item,price\n")
file.write("2020-02-07,Milk,26.5\n")
file.write("2020-02-08,Water,7\n")
file.close()

In [ ]:
header = ("date","item","price")
",".join(header) + "\n"

'date,item,price\n'

In [ ]:
header =("date","item","price")
content = [
    ("2020-02-07", "Milk","26.5"),
    ("2020-02-08", "Water","7"),
    ("2020-02-08", "Mask","20"),
    ("2020-02-08", "Lays","10"),
    ("2020-02-08", "Rice","6")
]
file = open('products.csv','w')
file.write(",".join(header)+ "\n")

for row in content:
  file.write(",".join(row)+"\n")

file.close()

In [ ]:
with open("products.csv", "r")as f:
  product = f.readlines()

product

['date,item,price\n',
 '2020-02-07,Milk,26.5\n',
 '2020-02-08,Water,7\n',
 '2020-02-08,Mask,20\n',
 '2020-02-08,Lays,10\n',
 '2020-02-08,Rice,6\n']

In [ ]:
len(product)

6

In [ ]:
import pandas as pd

df = pd.read_csv("sample_data/california_housing_test.csv")
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
3       -118.36     33.82                28.0         67.0            15.0   
4       -119.67     36.33                19.0       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
0         1537.0       606.0         6.6085            344700.0  
1          809.0       277.0         3.5990            176500.0  
2         1484.0       495.0         5.7934            270500.0  
3           49.0        11.0         6.1359            330000.0  
4          850.0       237.0         2.9375             81700.0  
...          ...         ...            ...                 ...  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0  

[3000 rows x 9 columns]

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.to_csv("new.data.csv")

In [ ]:
bool("false")

True

In [ ]:
import ast
ast.literal_eval("False")

False

In [ ]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [ ]:
import pandas as pd
w_restaurant = pd.read_csv('w_restaurant.csv')

In [ ]:
w_restaurant.head(5)

2  \
144976 น้ำหนาววัลเล่ย์           1 0 Phetchabun                  36180.0 w6bphng 0 3.0 NaN NaN    1 1 881   2   
144977 บาบีคิวรสเด็ด             1 0 Bangkok Metropolitan Region NaN     w4rw0b2 0 4.0 NaN 2.0    1 0 1458  0   
144978 ภูเมี่ยง                  4 0 Phitsanulok                 53110   w5peduv 0 0.0 NaN 2.0    0 0 479   0   
144979 กาแฟสดเพลิน Plearn Coffee 1 0 Chiang Mai                  50000.0 w5q6v5c 0 0.0 NaN NaN    0 0 386   1   
144980 บะหมี่เจ้เคี๊ยม           1 0 Bangkok Metropolitan Region NaN     w4rtdvd 0 0.0 NaN NaN    0 0 179   0   

                                                                                                            0  \
144976 น้ำหนาววัลเล่ย์           1 0 Phetchabun                  36180.0 w6bphng 0 3.0 NaN NaN    1 1 881   0   
144977 บาบีคิวรสเด็ด             1 0 Bangkok Metropolitan Region NaN     w4rw0b2 0 4.0 NaN 2.0    1 0 1458  0   
144978 ภูเมี่ยง                  4 0 Phitsanulok                 53110   w5peduv 0 0.0 NaN 2.0    0 0 479   0   
144979 กาแฟสดเพลิน Plearn Coffee 1 0 Chiang Mai                  50000.0 w5q6v5c 0 0.0 NaN NaN    0 0 386   0   
144980 บะหมี่เจ้เคี๊ยม           1 0 Bangkok Metropolitan Region NaN     w4rtdvd 0 0.0 NaN NaN    0 0 179   0   

                                                                                                            2.1  \
144976 น้ำหนาววัลเล่ย์           1 0 Phetchabun                  36180.0 w6bphng 0 3.0 NaN NaN    1 1 881     0   
144977 บาบีคิวรสเด็ด             1 0 Bangkok Metropolitan Region NaN     w4rw0b2 0 4.0 NaN 2.0    1 0 1458    0   
144978 ภูเมี่ยง                  4 0 Phitsanulok                 53110   w5peduv 0 0.0 NaN 2.0    0 0 479     0   
144979 กาแฟสดเพลิน Plearn Coffee 1 0 Chiang Mai                  50000.0 w5q6v5c 0 0.0 NaN NaN    0 0 386     1   
144980 บะหมี่เจ้เคี๊ยม           1 0 Bangkok Metropolitan Region NaN     w4rtdvd 0 0.0 NaN NaN    0 0 179     0   

                                                                                                           Steak House/Barbeque  \
144976 น้ำหนาววัลเล่ย์           1 0 Phetchabun                  36180.0 w6bphng 0 3.0 NaN NaN    1 1 881                  Thai   
144977 บาบีคิวรสเด็ด             1 0 Bangkok Metropolitan Region NaN     w4rw0b2 0 4.0 NaN 2.0    1 0 1458       Barbeque/Grill   
144978 ภูเมี่ยง                  4 0 Phitsanulok                 53110   w5peduv 0 0.0 NaN 2.0    0 0 479              Mountain   
144979 กาแฟสดเพลิน Plearn Coffee 1 0 Chiang Mai                  50000.0 w5q6v5c 0 0.0 NaN NaN    0 0 386      Café/Coffee Shop   
144980 บะหมี่เจ้เคี๊ยม           1 0 Bangkok Metropolitan Region NaN     w4rtdvd 0 0.0 NaN NaN    0 0 179               Noodles   

                                                                                                            1.0  \
144976 น้ำหนาววัลเล่ย์           1 0 Phetchabun                  36180.0 w6bphng 0 3.0 NaN NaN    1 1 881   3.0   
144977 บาบีคิวรสเด็ด             1 0 Bangkok Metropolitan Region NaN     w4rw0b2 0 4.0 NaN 2.0    1 0 1458  1.0   
144978 ภูเมี่ยง                  4 0 Phitsanulok                 53110   w5peduv 0 0.0 NaN 2.0    0 0 479   NaN   
144979 กาแฟสดเพลิน Plearn Coffee 1 0 Chiang Mai                  50000.0 w5q6v5c 0 0.0 NaN NaN    0 0 386   1.0   
144980 บะหมี่เจ้เคี๊ยม           1 0 Bangkok Metropolitan Region NaN     w4rtdvd 0 0.0 NaN NaN    0 0 179   1.0   

                                                                                                            Unnamed: 5  \
144976 น้ำหนาววัลเล่ย์           1 0 Phetchabun                  36180.0 w6bphng 0 3.0 NaN NaN    1 1 881          NaN   
144977 บาบีคิวรสเด็ด             1 0 Bangkok Metropolitan Region NaN     w4rw0b2 0 4.0 NaN 2.0    1 0 1458         NaN   
144978 ภูเมี่ยง                  4 0 Phitsanulok                 53110   w5peduv 0 0.0 NaN 2.0    0 0 479          NaN   
144979 กาแฟสดเพลิน Plearn Coffee 1 0 Chiang Mai                  50000.0 w5q6v5c 0 0.0 NaN Na

In [ ]:
#ขนาด dataset
print(w_restaurant.shape)

(151930, 18)


In [ ]:
select_column = ['id', 'name', 'weighted_average_rating']
w_restaurant_projection = w_restaurant.loc[:, select_column]
w_restaurant_projection.head(5)

KeyError: "None of [Index(['id', 'name', 'weighted_average_rating'], dtype='object')] are in the [columns]"

In [ ]:
condition = w_restaurant['name'].str.endswith('ดงมูลเหล็ก')
w_restaurant_selection = w_restaurant.loc[condition,:]
print(w_restaurant_selection.shape)
w_restaurant_selection.head(10)

KeyError: 'name'

In [ ]:
condition = w_restaurant['name'].str.contains('ขาหมู')
w_restaurant_selection = w_restaurant.loc[condition, :]
print(w_restaurant_selection.shape)
w_restaurant_selection.head(10)

KeyError: 'name'

In [ ]:
condition = w_restaurant['zipcode'].isna()
w_restaurant_selection = w_restaurant.loc[condition, :]
print(w_restaurant_selection.shape)
w_restaurant_selection.head(10)

KeyError: 'zipcode'

In [4]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [5]:
df = pd.read_csv('study.csv')
df.head()

Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30

In [6]:
df.columns

Index(['Hours', 'Scores'], dtype='object')

In [7]:
input_columns = ['Hours']
output_columns = ['Scores']

In [8]:
X = df.loc[:,input_columns]
Y = df.loc[:,output_columns]

In [21]:
#X.shape

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= .20, random_state=1,)

In [44]:
#Linear Regression
from sklearn.linear_model import LinearRegression
model1 = LinearRegression() # สร้าง model : y=mx+b
model1.fit(X_train, y_train) # train model

LinearRegression()

In [59]:
print(model1.intercept_)
print(model1.coef_)

[-5889.3730808]
[[246.43462275 300.89595729 254.64158627]]


In [46]:
y_p = model1.predict(X_test)

In [68]:
from sklearn import metrics
print(np.sqrt(metrics.mean_squared_error(y_test, y_p)))

11380.3421565389


In [73]:
X_quiz = [[7.5],[8.5],[9.25] ]
y_quiz = model1.predict(X_quiz)
print(y_quiz)

ValueError: X has 1 features, but LinearRegression is expecting 3 features as input.

In [74]:
#ใช้ model ที่ได้ หากเรียน 12.2 , 15.3, 1, 0 ,6,7.2
#จะได้คะแนนเท่าใด
X_quiz = [[12.2],[15.3],[1],[0],[6],[7.2] ]
y_quiz = model1.predict(X_quiz)
print(y_quiz)

ValueError: X has 1 features, but LinearRegression is expecting 3 features as input.

In [36]:
df = pd.read_csv('insurance.csv')
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [37]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [39]:
df.dropna(inplace = True)

In [40]:
input_columns = ['age', 'bmi', 'children']
output_columns = ['charges']

In [41]:
X = df.loc[:,input_columns]
y = df.loc[:,output_columns]

In [42]:
#X.shape

In [60]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .20, random_state = 1,)

In [63]:
from sklearn.linear_model import LinearRegression
model1 = LinearRegression()
model1.fit(X_train, y_train)

LinearRegression()

In [64]:
print(model1.intercept_)
print(model1.coef_)

[-5889.3730808]
[[246.43462275 300.89595729 254.64158627]]


In [66]:
y_p = model1.predict(X_test)
from sklearn import metrics
print(np.sqrt(metrics.mean_squared_error(y_test, y_p)))

11380.3421565389


In [67]:
X_quiz = [[30,35,1],[19,25,0],[41,23,2] ]
y_quiz = model1.predict(X_quiz)
print(y_quiz)

[[12289.66569339]
 [ 6315.28368389]
 [11644.33664242]]
